
name: 自动部署 # 步骤名称

on:
  push:
    branches:
      - master # 当 master 分支发生提交时触发
    # paths-ignore: # 避免这些文件改变时触发
    #   - README.md
    #   - LICENSE
    paths: # 指定哪些文件改变时触发
      - index.js
      - template/**
      - data/**

jobs:
  deploy:
    runs-on: ubuntu-latest # 指定用什么版本服务器来执行

    steps:
      - name: git checkout
        uses: actions/checkout@v3

      - name: npm install
        run: npm i

      - name: npm run deploy
        run: npm run deploy

      # - name: SSH 命令删除旧文件
      #   uses: appleboy/ssh-action@master
      #   with:
      #     # 这里配置对应仓库设置的变量，就可以避免服务器配置暴露
      #     host: ${{ secrets.SSH_HOST }}
      #     port: ${{ secrets.SSH_PORT }}
      #     username: ${{ secrets.SSH_USER }}
      #     key: ${{ secrets.DEPLOY_KEY }}

          # 先用 SSH 命令删除旧文件
          # script: |
          #   rm -rf /data/services/kaifage.com/index.html

      - name: sftp transfer
        uses: wlixcc/SFTP-Deploy-Action@master
        with:
          server: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          ssh_private_key: ${{ secrets.DEPLOY_KEY }}
          sftp_only: true
          # delete_remote_files: true  # 谨慎开启
          local_path: './dist/*'
          remote_path: '/data/github_actions/kaifage.com/'
